  - name: Skype | Check if is present
    command: test -x /usr/bin/skype
    when: ansible_system == "Linux"
    ignore_errors: yes
    register: skype_present
    tags:
      - skype

  - name: Skype | Add Debian apt repository
    apt_repository: repo="deb http://archive.canonical.com/ {{ ansible_distribution_release }} partner"
    when: skype_present|failed
    become: true
    tags:
      - skype

  - name: Skype | Install skype-bin dependency
    apt:  name=skype-bin state=present update-cache=yes
    when: skype_present|failed
    become: true
    tags:
      - skype


  - name: Skype | Install skype 4.3
    apt:  name=skype state=present update-cache=yes
    when: skype_present|failed
    become: true
    tags:
      - skype
